### ISSUE TITLE
Critical: Make this repo private

### ISSUE THREAD

**Issue by kundan2510** [apeeyush/xerox-challenge#1]
Make this repo private otherwise you'll receive mail like this: We recently found that your code used for XRCI challenge is hosted on https://github.com/apeeyush. As per the Intellectual Property agreement signed by all interns (including challenge participants), the code as well as the data cannot be published in any public website or forum without an official approval from Xerox. Kindly delete the code from the website as soon as possible and inform me.

LOL

**Comment by apeeyush** [comment]
This is for the hackerrank contest and not the actual challenge. I think we were allowed to release the code once the contest was over. Please inform if this is not the case. :P Closing this issue for now.

**Comment by kundan2510** [comment]
Yeah, you are right! My bad :P
